import { JSX, lazy } from 'react';

export interface RouteDefinition {
  title: string;
  tag: string;
  Element: React.LazyExoticComponent<() => JSX.Element>;
}

export interface SectionDefinition {
  'section-title': string;
  tag: string;
  pages: RouteDefinition[];
}

// that can be autogenerated, but for this repo for now we will hand-code it
export const RouteDefinitions: SectionDefinition[] = [
  {
    'section-title': 'Getting Started',
    tag: 'getting-started',
    pages: [
      {
        title: 'Overview',
        tag: 'overview',
        Element: lazy(() => import('./GettingStarted/GettingStarted')),
      },
    ],
  },
  {
    'section-title': 'Math Reference (@lunaterra/math)',
    tag: 'math',
    pages: [
      {
        title: 'V2',
        tag: 'v2',
        Element: lazy(() => import('./Math/V2')),
      },
      {
        title: 'M3',
        tag: 'm3',
        Element: lazy(() => import('./Math/M3')),
      },
      {
        title: 'Rect2D',
        tag: 'rect2d',
        Element: lazy(() => import('./Math/Rect2D')),
      },
      {
        title: 'Angles',
        tag: 'angles',
        Element: lazy(() => import('./Math/Angles')),
      },
      {
        title: 'Numbers',
        tag: 'numbers',
        Element: lazy(() => import('./Math/Numbers')),
      },
    ],
  },
  {
    'section-title': 'Core Concepts (@lunaterra/core)',
    tag: 'core',
    pages: [
      {
        title: 'Base',
        tag: 'base',
        Element: lazy(() => import('./Core/Base')),
      },
      {
        title: 'LTElement',
        tag: 'lt-element',
        Element: lazy(() => import('./Core/LTElement')),
      },
      {
        title: 'Zoom & Scale',
        tag: 'zoom-controls',
        Element: lazy(() => import('./Core/ZoomControls')),
      },
      {
        title: 'Constraints',
        tag: 'constraints',
        Element: lazy(() => import('./Core/Constraints')),
      },
      {
        title: 'ScaleRuler',
        tag: 'scale-ruler',
        Element: lazy(() => import('./Core/ScaleRuler')),
      },
    ],
  },
  {
    'section-title': 'Color Reference (@lunaterra/color)',
    tag: 'color',
    pages: [
      {
        title: 'Color',
        tag: 'color',
        Element: lazy(() => import('./Color/Color')),
      },
    ],
  },
  {
    'section-title': 'Elements Reference (@lunaterra/elements)',
    tag: 'elements',
    pages: [
      {
        title: 'Line',
        tag: 'line',
        Element: lazy(() => import('./Elements/Line')),
      },
      {
        title: 'Connectors',
        tag: 'connectors',
        Element: lazy(() => import('./Elements/LineConnectors')),
      },
      {
        title: 'Glow & Energy',
        tag: 'glow',
        Element: lazy(() => import('./Elements/LineGlow')),
      },
      {
        title: 'Grid',
        tag: 'grid',
        Element: lazy(() => import('./Elements/Grid')),
      },
      {
        title: 'Rect',
        tag: 'rect',
        Element: lazy(() => import('./Elements/Rect')),
      },
      {
        title: 'Interactive',
        tag: 'interactive',
        Element: lazy(() => import('./Elements/InteractiveLine')),
      },
    ],
  },
  {
    'section-title': 'Charts Reference (@lunaterra/charts)',
    tag: 'charts',
    pages: [
      {
        title: 'Axis',
        tag: 'axis',
        Element: lazy(() => import('./Charts/Axis')),
      },
      {
        title: 'Home Assistant',
        tag: 'home-assistant',
        Element: lazy(() => import('./Charts/HomeAssistant')),
      },
    ],
  }
];
