import { JSX, lazy } from 'react';

export interface RouteSearchEntry {
  title: string;
  anchor?: string;
  summary?: string;
  keywords?: string[];
}

export interface RouteDefinition {
  title: string;
  tag: string;
  Element: React.LazyExoticComponent<() => JSX.Element>;
  searchTerms?: string[];
  searchEntries?: RouteSearchEntry[];
}

export interface SectionDefinition {
  'section-title': string;
  tag: string;
  pages: RouteDefinition[];
}

// that can be autogenerated, but for this repo for now we will hand-code it
export const RouteDefinitions: SectionDefinition[] = [
  {
    'section-title': 'Getting Started',
    tag: 'getting-started',
    pages: [
      {
        title: 'Overview',
        tag: 'overview',
        Element: lazy(() => import('./GettingStarted/GettingStarted')),
      },
    ],
  },
  {
    'section-title': 'Math Reference (@lunaterra/math)',
    tag: 'math',
    pages: [
      {
        title: 'V2',
        tag: 'v2',
        Element: lazy(() => import('./Math/V2')),
        searchTerms: [
          'add',
          'sub',
          'scale',
          'dot',
          'length',
          'normalize',
          'distanceTo',
          'withinDistance',
          'angleTo',
          'setAngle',
          'setLenght',
          'shortenBy',
          'byElementDiv',
          'closestToLine',
          'angleBetweenPoints',
        ],
        searchEntries: [
          {
            title: 'V2.distanceTo',
            anchor: 'distance-to',
            summary: 'Returns the Euclidean distance between this point and another V2.',
            keywords: ['distance', 'distanceTo', 'euclidean distance', 'v2 distance'],
          },
          {
            title: 'V2.withinDistance',
            anchor: 'within-distance',
            summary: 'Checks whether another V2 lies within a distance threshold.',
            keywords: ['withinDistance', 'distance threshold', 'range test'],
          },
          {
            title: 'V2.add',
            anchor: 'add',
            summary: 'Returns the component-wise sum of two vectors.',
            keywords: ['add', 'vector addition', 'sum'],
          },
          {
            title: 'V2.sub',
            anchor: 'sub',
            summary: 'Returns the component-wise difference of two vectors.',
            keywords: ['sub', 'subtract', 'difference'],
          },
          {
            title: 'V2.normalize',
            anchor: 'normalize',
            summary: 'Returns a unit vector in the same direction.',
            keywords: ['normalize', 'unit vector'],
          },
          {
            title: 'V2.dot',
            anchor: 'dot',
            summary: 'Computes the scalar dot product.',
            keywords: ['dot', 'dot product', 'projection'],
          },
          {
            title: 'V2.angleTo',
            anchor: 'angle-to',
            summary: 'Returns the angle of the displacement from this point to another.',
            keywords: ['angleTo', 'angle', 'direction'],
          },
          {
            title: 'V2.closestToLine',
            anchor: 'closest-to-line',
            summary: 'Returns the closest point on a line segment to a query point.',
            keywords: ['closestToLine', 'projection', 'line distance'],
          },
        ],
      },
      {
        title: 'M3',
        tag: 'm3',
        Element: lazy(() => import('./Math/M3')),
      },
      {
        title: 'Rect2D',
        tag: 'rect2d',
        Element: lazy(() => import('./Math/Rect2D')),
        searchTerms: ['contains', 'intersects', 'quadrant', 'bottomLeft', 'topRight', 'center', 'width', 'height'],
      },
      {
        title: 'Angles',
        tag: 'angles',
        Element: lazy(() => import('./Math/Angles')),
      },
      {
        title: 'Numbers',
        tag: 'numbers',
        Element: lazy(() => import('./Math/Numbers')),
      },
    ],
  },
  {
    'section-title': 'Core Concepts (@lunaterra/core)',
    tag: 'core',
    pages: [
      {
        title: 'Engine & Renderers',
        tag: 'base',
        Element: lazy(() => import('./Core/Base')),
        searchTerms: [
          'mouse',
          'click',
          'pointer',
          'drag',
          'mouseHandlers',
          'activateEditMode',
          'activateItemDragMode',
          '$clicksWorld',
          '$mousePositionWorld',
          '$mouseDraggingFromWorld',
        ],
        searchEntries: [
          {
            title: 'engine.activateEditMode',
            anchor: 'pointer-input',
            summary: 'High-level click and drag session API for interactive tools.',
            keywords: ['click', 'mouse click', 'edit mode', 'pointer input', 'interactive tool'],
          },
          {
            title: 'renderer.mouseHandlers.$clicksWorld',
            anchor: 'pointer-input',
            summary: 'Observable stream of click events in world coordinates.',
            keywords: ['$clicksWorld', 'mouse click', 'world click', 'click listener'],
          },
          {
            title: 'renderer.mouseHandlers.$mousePositionWorld',
            anchor: 'pointer-input',
            summary: 'Observable stream of pointer positions in world coordinates.',
            keywords: ['$mousePositionWorld', 'mouse move', 'pointer move', 'hover'],
          },
          {
            title: 'engine.activateItemDragMode',
            anchor: 'pointer-input',
            summary: 'Typed drag capture API with hover, start, move, and end callbacks.',
            keywords: ['drag', 'item drag', 'onDragStart', 'onDragEnd', 'hitTest'],
          },
        ],
      },
      {
        title: 'LTElement',
        tag: 'lt-element',
        Element: lazy(() => import('./Core/LTElement')),
      },
      {
        title: 'Zoom & Scale',
        tag: 'zoom-controls',
        Element: lazy(() => import('./Core/ZoomControls')),
      },
      {
        title: 'Constraints',
        tag: 'constraints',
        Element: lazy(() => import('./Core/Constraints')),
      },
      {
        title: 'ScaleRuler',
        tag: 'scale-ruler',
        Element: lazy(() => import('./Core/ScaleRuler')),
      },
    ],
  },
  {
    'section-title': 'Color Reference (@lunaterra/color)',
    tag: 'color',
    pages: [
      {
        title: 'Color',
        tag: 'color',
        Element: lazy(() => import('./Color/Color')),
      },
    ],
  },
  {
    'section-title': 'Elements Reference (@lunaterra/elements)',
    tag: 'elements',
    pages: [
      {
        title: 'Line',
        tag: 'line',
        Element: lazy(() => import('./Elements/Line')),
      },
      {
        title: 'Connectors',
        tag: 'connectors',
        Element: lazy(() => import('./Elements/LineConnectors')),
      },
      {
        title: 'Glow & Energy',
        tag: 'glow',
        Element: lazy(() => import('./Elements/LineGlow')),
      },
      {
        title: 'Grid',
        tag: 'grid',
        Element: lazy(() => import('./Elements/Grid')),
      },
      {
        title: 'Rect',
        tag: 'rect',
        Element: lazy(() => import('./Elements/Rect')),
      },
      {
        title: 'Interactive',
        tag: 'interactive',
        Element: lazy(() => import('./Elements/InteractiveLine')),
      },
    ],
  },
  {
    'section-title': 'Charts Reference (@lunaterra/charts)',
    tag: 'charts',
    pages: [
      {
        title: 'Axis',
        tag: 'axis',
        Element: lazy(() => import('./Charts/Axis')),
      },
      {
        title: 'Home Assistant',
        tag: 'home-assistant',
        Element: lazy(() => import('./Charts/HomeAssistant')),
      },
    ],
  }
];
